title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: hyde

url: https://chenavin.github.io

aux_links:
  Template Repository: https://github.com/chenavin
