title: Chen Avin homepage
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://chenavin.github.io

aux_links:
  Template Repository: https://github.com/chenavin
